variables:
    FQ_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/pipeline_image"

image: "${FQ_IMAGE_NAME}"

stages:
  - build
  - test
  
# Select what we should cache between builds
cache:
  paths:
    - vendor/

build_pipeline_image:
    stage: build
    cache:
        policy: pull
    only:
          - schedules
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    variables:
        FQ_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/pipeline_image"
    script:
        - mkdir -p /kaniko/.docker
        # yamllint disable-line rule:line-length
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
        - >
            /kaniko/executor
            --context $CI_PROJECT_DIR
            --dockerfile $CI_PROJECT_DIR/Dockerfile
            --destination $FQ_IMAGE_NAME

# Run our tests
# If Xdebug was installed you can generate a coverage report and see code coverage metrics.
test:
  stage: test
  script:
    - php /composer.phar require horde/test ^3
    - php /composer.phar require horde/rdo ^3
    - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never
    
