---
id: Dns
name: Dns
full: Horde Domain Name System library
description: Libraries for configuring DNS servers
list: dev
type: library
authors:
  -
    name: Ralf Lang
    user: rlang
    email: lang@b1-systems.de
    active: true
    role: lead
  -
    name: Diana Hille
    user: hille
    email: hille@b1-systems.de
    active: true
    role: lead
version:
  release: 1.0.0alpha1
  api: 1.0.0
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7 || ^8
    composer:
      horde/rdo: ^3
      aws/aws-sdk-php: ^3
  dev:
    composer:
      horde/test: ^3
autoload:
    psr-0:
      Horde_DNS: lib/
    psr-4:
      Horde\Dns\: src/
